### ISSUE TITLE
How to download the documents of the filtered diseases in the generated list? 

### ISSUE THREAD

**Issue by guanchuwang** [PittNAIL/llms-vote#2] opened 2023-09-24 21:47 UTC
Thanks for releasing this fantastic dataset! Also, thank you for replying to our previous issue. We wanted to let you know that we followed your instructions to generate a list of rare diseases. The generated rare_disease.txt file contains the name of the disease like this:

"""
48,XXYY syndrome
Ataxia-telangiectasia
Ocular albinism with late-onset sensorineural deafness
Extraneural perineurioma
Intraneural perineurioma
Lissencephaly with cerebellar hypoplasia type A
Lissencephaly with cerebellar hypoplasia type B
Lissencephaly with cerebellar hypoplasia type C
Lissencephaly with cerebellar hypoplasia type D
......
"""

Since we sincerely hope to reproduce the experiment of few-shot learning and evaluation in your paper, could you tell us where to download the documents of the filtered diseases in the generated list? 

Thanks in advance!

**Comment by oniani** [comment] 2023-09-25 00:41
You would first need to get [MIMIC-IV](https://physionet.org/content/mimiciv/2.2/). That also needs signing MIMIC-IV Data Use Agreement (DUA). Once you obtain the dataset, you can generate the inverted index by running the Rust program (so make sure you also have [Rust installed](https://www.rust-lang.org/tools/install)).

```console
Usage: inverted_index <RARE_DISEASE_DATA> <MIMIC_IV_DISCHARGE_DATA> <OUT_JSON_PATH>
```

And you can run the program as follows:

```console
$ cargo run --release -- path_to_rare_disease.txt path_to_discharge.csv inverted_index.json
```

**Comment by oniani** [comment] 2023-09-25 00:51
Also, thanks for pointing this out! I have now updated the [README](https://github.com/oniani/llms-vote/blob/main/README.md) to include the instructions on reproducing the inverted index.

**Comment by lixiangtnt** [comment] 2024-01-10 07:45
I'm facing a similar challenge in reproducing data from the MIMIC-IV dataset. My current folder structure of MIMIC-IV looks like this:

host
icu
licences.txt
changelog.txt

Could you guide me through the procedure to generate the 'MIMIC_IV_DISCHARGE_DATA'? I need help in for this approach. Many thanks.

**Comment by oniani** [comment] 2024-01-23 02:02
I assume this issue was resolved. Closing this now, but feel to open a new issue if needed.

**Closed as completed by oniani** 2024-01-23 02:02 UTC
